<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTpzxMQO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTpzxMQO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTpzxMQO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTpzxMQO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTpzxMQO\App_KernelDevDebugContainer([
    'container.build_hash' => 'TpzxMQO',
    'container.build_id' => 'cd8fe20e',
    'container.build_time' => 1610961112,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTpzxMQO');
