<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGGJUx1C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGGJUx1C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGGJUx1C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGGJUx1C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGGJUx1C\App_KernelDevDebugContainer([
    'container.build_hash' => 'GGJUx1C',
    'container.build_id' => 'e470926c',
    'container.build_time' => 1606204702,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGGJUx1C');
